### ISSUE TITLE
Change rule for Polarity

### ISSUE THREAD

**Issue by kajad** [clarinsi/jos2ud#3]
Previously, the Polarity=Neg feature has been attributed to particle 'ne' as a negation particle in verb phrases (e.g. _tega ne vem_), as a rule in the `convert_dependencies.py` script. Now, the Polarity=Neg feature should be attributed to all occurrences of the particle 'ne', as part of the morphology conversion script (for both ssj500k corpus and Sloleks lexicon).

**Comment by TomazErjavec** [comment]
Implemented in cfd5680.
