### ISSUE TITLE
Implementation of Z-do-DET and R-to-DET lists

### ISSUE THREAD

**Issue by kajad** [clarinsi/jos2ud#6]
Checking whether the new ssj500k/Sloleks conversion scripts implement the lists of JOS-adverbs (R) and JOS-pronouns (Z) that always convert to DET. They were sent to @TomazErjavec on Nov 6th 2018 (subject 'UD: nadaljevanje'). If not, they should be.

**Comment by TomazErjavec** [comment]
They are, cf. jos2ud-pos.tbl "#New batch by Kaja".
