### ISSUE TITLE
Re-examine DET

### ISSUE THREAD

**Issue by kajad** [clarinsi/jos2ud#7]
After looking at the output of the new conversion scripts, it seems that the list of determiners from JOS-advers and JOS-pronouns should be re-evaluated by @kajad, i.e. _oni_, _vse_ ... When this is done, new lists should be reported to @TomazErjavec to update the` jos2ud-pos.tbl` script.

**Comment by kajad** [comment]
@TomazErjavec, please update the rules in jos2ud-pos.tbl, so that:

- JOS-pronouns with lemma _oni_ and _un_ are tagged as `DET ` (not ADV)
- JOS-adverbs with lemma _enako, ful, maksimalno, majčkeno, malce, minimalno, najmanj, nekoliko, nemalo, nič, polno, precej, premalo, večidel, vse, zadosti_ are tagged as `ADV` (not DET)

A re-examination of these items in ssj500k has shown that Mija has mis-interpreted them as DET, i.e. items that mostly appear as noun modifiers (they don't).

**Comment by TomazErjavec** [comment]
Done in 7ab7017.
